--CREATE TABLE foodconfig
--(
--	idt INT PRIMARY KEY IDENTITY(1,1),
--	email VARCHAR(MAX) NULL,
--	username VARCHAR(MAX) NULL,
--	passsword VARCHAR(MAX) NULL,
--	tenmonan VARCHAR(MAX) NULL,
--	gia INT NULL,
--	mota VARCHAR(MAX) NULL,
--	hinhanh VARCHAR(MAX) NULL,
--	diachi VARCHAR(MAX) NULL

--)